#!/bin/bash 

#PBS -l nodes=1:ppn=16 
#PBS -l walltime=120:00:00 
#PBS -m ae 
#PBS -M ccaiafa@iu.edu 
#PBS -N comp_4c_010
#PBS -V 
#PBS -o /N/dc2/projects/lifebid/code/ccaiafa/Shells/code/Shell_Mass/Scripts_paper/comp_4c_010.out 
#PBS -e /N/dc2/projects/lifebid/code/ccaiafa/Shells/code/Shell_Mass/Scripts_paper/comp_4c_010.err 

module load matlab 
cd /N/dc2/projects/lifebid/code/ccaiafa/Shells/code/Shell_Mass/Scripts_paper/

matlab -nodesktop -nosplash -r 'Compute_4c_total_010'  
