#!/bin/bash
#PBS -l nodes=1:ppn=32
#PBS -l walltime=72:00:00
#PBS - gres=ccm
#PBS -m ae
#PBS -M ccaiafa@iu.edu
#PBS -N compute_4c
#PBS -V
#PBS -o /N/dc2/projects/lifebid/code/ccaiafa/Shells/code/Shell_Mass/Scripts_paper/compute_4c_BigRed2.out 
#PBS -e /N/dc2/projects/lifebid/code/ccaiafa/Shells/code/Shell_Mass/Scripts_paper/compute_4c_BigRed2.err 


cd /N/dc2/projects/lifebid/code/ccaiafa/Shells/code/Shell_Mass/Scripts_paper/
ccmrun matlab -nodesktop -nosplash -r 'Compute_4c_total' 
