cd ..
code_path = pwd;
addpath(genpath(code_path));

cd ../..
root = pwd;
InputPath = strcat(root,'/code/Shell_Mass/Results');
dataRootPath = strcat(root,'/data');

%% 3c
shells = load_shells_3c_total();

dataOutPath = InputPath;
filename = fullfile(dataOutPath,'Table_Input_3c.txt');
fileID = fopen(filename,'w');
fprintf(fileID,'Name   \t long \t lat \t X0 \t Y0 \t a \t b \t tita \t V0 \t dV \t D \t MassMiss  \t MassShell \n');
for n=1:length(shells)
    fprintf(fileID,'%s   \t %12.1f \t %12.1f \t %12.1f \t %12.1f \t %12.1f \t %12.1f \t %12.1f \t %12.1f \t %12.1f \t %12.1f \t %12.1f \n', ...
        shells{n}.name, ...
        shells{n}.long, ...
        shells{n}.lat, ...
        shells{n}.X0, ...
        shells{n}.Y0, ...        
        shells{n}.a, ...
        shells{n}.b, ...
        shells{n}.tita, ...
        shells{n}.V0, ...
        shells{n}.dV, ...
        shells{n}.D, ...
        shells{n}.MassMiss, ...
        shells{n}.MassShell);
end
fclose(fileID);

%% 4c
shells = load_shells_4c_total();

dataOutPath = InputPath;
filename = fullfile(dataOutPath,'Table_Input_4c.txt');
fileID = fopen(filename,'w');
fprintf(fileID,'Name   \t long \t lat \t X0 \t Y0 \t a \t b \t tita \t V0 \t dV \t D \t MassMiss  \t MassShell \n');
for n=1:length(shells)
    fprintf(fileID,'%s   \t %12.1f \t %12.1f \t %12.1f \t %12.1f \t %12.1f \t %12.1f \t %12.1f \t %12.1f \t %12.1f \t %12.1f \t %12.1f \n', ...
        shells{n}.name, ...
        shells{n}.long, ...
        shells{n}.lat, ...
        shells{n}.X0, ...
        shells{n}.Y0, ...        
        shells{n}.a, ...
        shells{n}.b, ...
        shells{n}.tita, ...
        shells{n}.V0, ...
        shells{n}.dV, ...
        shells{n}.D, ...
        shells{n}.MassMiss, ...
        shells{n}.MassShell);
end
fclose(fileID);


